python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
python: can't open file '/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main22.py': [Errno 2] No such file or directory
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
usage: main2.py [-h] [-mu MU] [-T T] [-N N] [-k K] [--job JOB] [--store]
                [--print] [--alpha ALPHA] [--level LEVEL] [--dim DIM]
main2.py: error: argument --level: invalid int value: '{0}'
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
Traceback (most recent call last):
  File "/net/st1/export/clusterhome/nonosaha/PythonCodes/CubicPuzzle/scripts/../src/main2.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
./run_mu.sh: line 7: alph_analysis.py: command not found
solved for mu=: 
